In [1]:
import requests
import json
import pandas as pd
import numpy as np

In [2]:
starships_lst = []
for p in range(4):
    url = "https://swapi.dev/api/starships/?page="+str(p+1)
    response = requests.get(url).json()
    starships = response["results"]
    for starship in starships:
        starship["no_of_films"] = len(starship["films"])
        if len(starship["pilots"])>0:
            pilot_url = starship["pilots"][0]
            response = requests.get(pilot_url).json()
            starship["main_pilot"] = response["name"]
        else:
            starship["main_pilot"] = "No Pilot"
        starships_lst.append(starship)

In [34]:
starships_df = pd.DataFrame(starships_lst)
starships_df.T
target_cols = ["name", "manufacturer", "crew", "passengers", "cargo_capacity", "starship_class", "main_pilot"]
starships_df = starships_df[target_cols]
starships_df.replace("unknown",np.nan, inplace=True)
starships_df.dropna(inplace=True)
starships_df["cargo_capacity"].replace("none",0, inplace=True)
starships_df["crew"] = starships_df["crew"].str.replace(',','')
starships_df["passengers"] = starships_df["passengers"].str.replace(',','')
starships_df.loc[0,"crew"]=30
starships_df.loc[1,"passengers"]=0

In [35]:
starships_df["crew"] = starships_df['crew'].astype('int64')
starships_df["passengers"] = starships_df['passengers'].astype('int64')
starships_df["cargo_capacity"] = starships_df['cargo_capacity'].astype('int64')

In [38]:
starships_df["artifact"]="ss"
starships_df

,name,manufacturer,crew,passengers,cargo_capacity,starship_class,main_pilot,artifact
0,CR90 corvette,Corellian Engineering Corporation,30,600,3000000,corvette,No Pilot,ss
1,Star Destroyer,Kuat Drive Yards,47060,0,36000000,Star Destroyer,No Pilot,ss
2,Sentinel-class landing craft,"Sienar Fleet Systems, Cyngus Spaceworks",5,75,180000,landing craft,No Pilot,ss
3,Death Star,"Imperial Department of Military Research, Sien...",342953,843342,1000000000000,Deep Space Mobile Battlestation,No Pilot,ss
4,Millennium Falcon,Corellian Engineering Corporation,4,6,100000,Light freighter,Chewbacca,ss
5,Y-wing,Koensayr Manufacturing,2,0,110,assault starfighter,No Pilot,ss
6,X-wing,Incom Corporation,1,0,110,Starfighter,Luke Skywalker,ss
7,TIE Advanced x1,Sienar Fleet Systems,1,0,150,Starfighter,Darth Vader,ss
8,Executor,"Kuat Drive Yards, Fondor Shipyards",279144,38000,250000000,Star dreadnought,No Pilot,ss
9,Rebel transport,"Gallofree Yards, Inc.",6,90,19000000,Medium transport,No Pilot,ss
10,Slave 1,Kuat Systems Engineering,1,6,70000,Patrol craft,Boba Fett,ss
11,Imperial shuttle,Sienar Fleet Systems,6,20,80000,Armed government transport,Luke Skywalker,ss
12,EF76 Nebulon-B escort frigate,Kuat Drive Yards,854,75,6000000,Escort ship,No Pilot,ss
14,A-wing,"Alliance Underground Engineering, Incom Corpor...",1,0,40,Starfighter,Arvel Crynyd,ss
15,B-wing,Slayn & Korpil,1,0,45,Assault Starfighter,No Pilot,ss
17,Droid control ship,"Hoersch-Kessel Drive, Inc.",175,139000,4000000000,Droid control ship,No Pilot,ss
18,Naboo fighter,Theed Palace Space Vessel Engineering Corps,1,0,65,Starfighter,Anakin Skywalker,ss
20,Scimitar,Republic Sienar Systems,1,6,2500000,Space Transport,Darth Maul,ss
23,Jedi starfighter,Kuat Systems Engineering,1,0,60,Starfighter,Obi-Wan Kenobi,ss
25,Republic Assault ship,Rothana Heavy Engineering,700,16000,11250000,assault ship,No Pilot,ss
26,Solar Sailer,Huppla Pasa Tisc Shipwrights Collective,3,11,240,yacht,No Pilot,ss
27,Trade Federation cruiser,"Rendili StarDrive, Free Dac Volunteers Enginee...",600,48247,50000000,capital ship,Obi-Wan Kenobi,ss
28,Theta-class T-2c shuttle,Cygnus Spaceworks,5,16,50000,transport,No Pilot,ss
29,Republic attack cruiser,"Kuat Drive Yards, Allanteen Six shipyards",7400,2000,20000000,star destroyer,No Pilot,ss
31,Jedi Interceptor,Kuat Systems Engineering,1,0,60,starfighter,Obi-Wan Kenobi,ss
32,arc-170,"Incom Corporation, Subpro Corporation",3,0,110,starfighter,No Pilot,ss
34,Belbullab-22 starfighter,Feethan Ottraw Scalable Assemblies,1,0,140,starfighter,Obi-Wan Kenobi,ss
35,V-wing,Kuat Systems Engineering,1,0,60,starfighter,No Pilot,ss